polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name="vote"),
    path('add_question/', views.add_question, name="add_question"),
    path('published_questions/', views.PublishedQuestionsView.as_view(), name="published_questions"),

]

sondage/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=255, unique=True)
    pub_date = models.DateTimeField('date published')

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description= 'Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models

# Create your models here.

polls/forms.py
from django.forms import ModelForm
from polls.models import Question

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']
        

        
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.utils import timezone
from django.forms import modelformset_factory

from .models import Question, Choice
from .forms import QuestionForm

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last 5 published questions up until now(not including future questions)."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date').exclude(choice__isnull=True)[:5]


class PublishedQuestionsView(generic.ListView):
    template_name = 'polls/published_questions.html'
    context_object_name = 'published_questions_list'
    
    def get_queryset(self):
        """Return all published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date').exclude(choice__isnull=True)


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """Excludes questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True)



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """Exclude all questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True)


def vote(request, question_id):
    """Voting page for question choices."""
    queryset = Question.objects.filter(pub_date__lte=timezone.now()).exclude(choice__isnull=True)
    question = get_object_or_404(queryset, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {'question': question, "error_message": "You didn't select a choice."})
    else:
        # To avoid race condition
        selected_choice.vote = F("vote") + 1
        selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

def add_question(request):
    """Add new question with choices"""
    ChoiceFormSet = modelformset_factory(Choice, fields=('choice_text',), extra=3,)
    if request.method == 'POST':
        question_form = QuestionForm(request.POST)
        choice_formset = ChoiceFormSet(request.POST)
        if question_form.is_valid() and choice_formset.is_valid():
            question = question_form.save()
            choices = choice_formset.save(commit=False)
            for choice in choices:
                choice.question = question
                choice.save()
            return HttpResponseRedirect(reverse("polls:index"))
    else:
        question_form = QuestionForm()
        choice_formset = ChoiceFormSet(queryset=Choice.objects.none())
    return render(request, 'polls/add_question.html', {'question_form': question_form, 'choice_formset': choice_formset})

users/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/polls/add_question.html
<form action="{% url 'polls:add_question' %}" method='post'>
    {% csrf_token %}
    <h1> Add a question </h1>
    {{ question_form }}
    {{ form}}
    {{ choice_formset.management_form}}
    <table>
        {% for form in choice_formset %}
        {{ form.as_table }}
        {% endfor %}
    </table>
    <input type="Submit" value="Post Question">
</form>

polls/templates/polls/detail.html
<form action="{% url "polls:vote" question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="{{ forloop.counter }}"> 
            {{ choice.choice_text }}
        </label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">Back to Questions</a>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}"
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}</ul>
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/published_questions.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}"
{% if published_questions_list %}
    <ul>
        {% for question in published_questions_list %}</ul>
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1> {{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} - {{ choice.vote }}vote{{ choice.vote|pluralize }}
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again</a> -
<a href="{% url 'polls:index' %}">Back to Questions</a>